feat: add critical tag to S3 modules
cds-snc/terraform-modules pull request #208
Opened 2023-02-20 19:47 UTC by gcharest

# Summary | Résumé

Attempt to add the `Critical:false` tag to all S3 buckets using the S3 modules.

2023-02-20 19:52 UTC, gcharest commented
Partially addresses https://github.com/cds-snc/security-risk-register/issues/47

2023-02-21 01:39 UTC, patheard reviewed
I like this idea to prevent accidental deletion.  Was the plan to add the value of these two variables to the bucket tags here?
https://github.com/cds-snc/terraform-modules/blob/7c7738acbbb70d4297c91e1799b02df3e374fdf2/S3/locals.tf#L2-L5

2023-02-21 14:01 UTC, gcharest commented
@patheard Yes, the goal would be to be able to enable this tag and create the proper SCPs pulling resources type + tag to apply them. Not there yet though, just at the flag stage atm!

2023-02-21 15:07 UTC, CalvinRodo requested changes
See changes about input.

2023-02-21 15:07 UTC, CalvinRodo commented on S3/input.tf
> +  type        = string
Change this to `boolean`

2023-02-21 15:07 UTC, CalvinRodo commented on S3/locals.tf
> +    (var.critical_tag_key) = var.critical_tag_value
(var.critical_tag_key) = var.critical_tag_value ? "true": "false"

2023-02-21 15:25 UTC, gcharest commented on S3/input.tf
> +  type        = string
done

2023-02-21 15:28 UTC, gcharest commented on S3/locals.tf
> +    (var.critical_tag_key) = var.critical_tag_value
updated as discussed

2023-02-21 15:30 UTC, CalvinRodo approved these changes
:taco::cat:

2023-02-21 15:53 UTC, gcharest commented
@CalvinRodo I borked the rebased to sign the very first commit so had to do a forced push, erasing the history of the previous commits.

2023-02-21 15:55 UTC, merged