feat: allow HTTPS egress from the VPC
cds-snc/terraform-modules pull request #58
Opened 2021-08-28 19:27 UTC by patheard

# Summary
This allows resources in the VPC to connect out on port 443, both
in the public subnet through the Internet Gateway (IGW), and from the
private subnets through the NAT Gateway to IGW.

The `allow` for the ephemeral ports is because NAT Gateway uses them
to track the network address translation.  The rules are based on this
[NACL guide](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-access-internet-with-NAT-gateway/).

It also includes a fix which prevents the flow log CloudWatch log group
from being recreated after it has been deleted.

2021-08-29 16:10 UTC, CalvinRodo requested changes
See Comment

2021-08-29 19:19 UTC, patheard commented on vpc/nacl.tf
> +}
Good point about the naming.  I like that idea of two variables `allow_https_ingress` & `allow_https_egress` to control both pieces of the flow.

2021-08-30 14:21 UTC, patheard commented on vpc/nacl.tf
> +}
I ended up going with 4 variables and updating the PR description with the new behaviour.

2021-08-31 13:32 UTC, CalvinRodo approved these changes
Minor non-blocking comment, allow_https_response is correct but the ephemeral port ranges aren't just used for https responses it can be used for a lot of stuff, so wouldn't hurt to tweak the name but not needed.

2021-08-31 14:00 UTC, merged